admin_app/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name='admin_app'

urlpatterns = [
    path('dashboard',views.dashboard,name='dashboard'),
    path('adminhome',views.admin_home,name='adminhome'),
    path('studentdetails',views.studentdetails,name='student'),
    path('addstudent',views.addstudent,name='newstudent'),
    path('staff',views.staffdetails,name='staff'),
    path('newstaff',views.addstaff,name='newstaff'),
    
]

app1/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name='app1'

urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.erp_login,name='login'),
    path('about',views.about,name='about'),
    path('admission',views.admission,name='admission'),
    path('gallery',views.gallery,name='gallery'),
    path('signup',views.signup,name='signup')
]

school_mgt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('adminapp/',include('admin_app.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()

admin_app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

admin_app/views.py
from django.shortcuts import render

# Create your views here.

def dashboard(request):
    return render(request,'dashboard.html')

def admin_home(request):
    return render(request,'admin_home.html')

def studentdetails(request):
    return render(request,'studentdetails.html')
def addstudent(request):
    return render(request,'addstudent.html')
def staffdetails(request):
    return render(request,'staffdetails.html')
def addstaff(request):
    return render(request,'addstaff.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def  index(request):
    return render(request,'index.html')
def about(request):
    return render(request,'about.html')
def admission(request):
    return render(request,'admission.html')
def gallery(request):
    return render(request,'gallery.html')


def erp_login(request):
    return render(request,'erp-login.html')
def signup(request):
    return render(request,'signup.html')

admin_app/templates/admin_home.html
{% extends 'master.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h3>School managemnet System Quick Icons</h3>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-header">
                <div class="icon icon-warning">
                    <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/000000/external-student-student-counselor-inipagistudio-lineal-color-inipagistudio.png"/>
                </div><br>
            </div>
            <div class="card-content"><br>
                <p class="category"><strong>  Students</strong></p>
                
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a href="{% url 'admin_app:student' %}">See detailed report</a>&nbsp;&nbsp;
                    <i class="material-icons">arrow_forward</i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-header">
                <div class="icon icon-rose">
                    <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/000000/external-teacher-language-learning-inipagistudio-lineal-color-inipagistudio.png"/>
                </div><br>
            </div>
            <div class="card-content"><br>
                <p class="category"><strong>Total Teachers</strong></p>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a href="{% url 'admin_app:staff' %}">See detailed report</a>&nbsp;&nbsp;
                    <i class="material-icons">arrow_forward</i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-header">
                <div class="icon icon-success">
                    <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/000000/external-parents-school-counseling-inipagistudio-lineal-color-inipagistudio.png"/>

                </div><br>
            </div>
            <div class="card-content"><br>
                <p class="category"><strong>Parents</strong></p>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                    <i class="material-icons">arrow_forward</i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
            <div class="card-header">
                <div class="icon icon-info">
                    <img src="https://img.icons8.com/external-icongeek26-outline-gradient-icongeek26/64/000000/external-events-donation-and-charity-icongeek26-outline-gradient-icongeek26.png"/>
                </div><br>
            </div>
            <div class="card-content"><br>
                <p class="category"><strong>Events</strong></p>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                    <i class="material-icons">arrow_forward</i>
                </div>
            </div>
        </div>
    </div>
    </div>
    <section>
        <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header">
                    <div class="icon icon-warning">
                        <img src="https://img.icons8.com/external-photo3ideastudio-gradient-photo3ideastudio/64/4a90e2/external-exam-online-learning-photo3ideastudio-gradient-photo3ideastudio-1.png"/>
                    </div><br>
                </div>
                <div class="card-content"><br>
                    <p class="category"><strong>EXam Schedules</strong></p>
                    
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                        <i class="material-icons">arrow_forward</i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header">
                    <div class="icon icon-warning">
                        <img src="https://img.icons8.com/external-icongeek26-outline-gradient-icongeek26/64/4a90e2/external-immigration-airport-icongeek26-outline-gradient-icongeek26-1.png"/>
                    </div><br>
                </div>
                <div class="card-content"><br>
                    <p class="category"><strong>Attendance</strong></p>
                    
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                        <i class="material-icons">arrow_forward</i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header">
                    <div class="icon icon-warning">
                        <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/4a90e2/external-medical-report-medical-test-inipagistudio-lineal-color-inipagistudio.png"/>
                    </div><br>
                </div>
                <div class="card-content"><br>
                    <p class="category"><strong>Mark</strong></p>
                    
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                        <i class="material-icons">arrow_forward</i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header">
                    <div class="icon icon-warning">
                        <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/4a90e2/external-class-student-activity-inipagistudio-lineal-color-inipagistudio.png"/>
                    </div><br>
                </div>
                <div class="card-content"><br>
                    <p class="category"><strong>Class List</strong></p>
                    
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                        <i class="material-icons">arrow_forward</i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                    <div class="card-header">
                        <div class="icon icon-warning">
                            <img src="https://img.icons8.com/external-inipagistudio-lineal-color-inipagistudio/64/4a90e2/external-payment-retail-company-inipagistudio-lineal-color-inipagistudio.png"/>
                        </div><br>
                    </div>
                    <div class="card-content"><br>
                        <p class="category"><strong>Payment</strong></p>
                        
                    </div>
                    <div class="card-footer">
                        <div class="stats">
                            <a href="#pablo">See detailed report</a>&nbsp;&nbsp;
                            <i class="material-icons">arrow_forward</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
    
</div>

{% endblock %}

admin_app/templates/staffdetails.html
{% extends 'master.html' %}
{% block content %}

<link rel="stylesheet" href="/static/css/admin/student.css">
<!-- <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script> -->


<script type="text/javascript">
$(document).ready(function()
{
 // Activate tooltip
 $('[data-toggle="tooltip"]').tooltip();
 
 // Select/Deselect checkboxes
 var checkbox = $('table tbody input[type="checkbox"]');
 $("#selectAll").click(function()
 {
  if(this.checked){
   checkbox.each(function()
   {
    this.checked = true;                        
   });
  }
  else
  {
   checkbox.each(function()
   {
    this.checked = false;                        
   });
  } 
 });
 checkbox.click(function()
 {
  if(!this.checked)
  {
   $("#selectAll").prop("checked", false);
  }
 });
});
</script>

<div class="container-fluid">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Manage <b> Teachers</b></h2>
                </div>
                <div class="col-sm-6">
                    <!-- todo cancel the modal -->
                    <a href="#" class="btn btn-success" ><i class="material-icons">&#xE147;</i> <span>Add Attandance</span></a>
                    <a href="{% url 'admin_app:newstaff' %}" class="btn btn-success" ><i class="material-icons">&#xE147;</i> <span>Add New Teachers</span></a>
                    <a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>      
                </div>
            </div>
        </div>
        <!-- Table starting     -->
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                        </span>
                    </th>
                    <th>Staff Name</th>
                    <th>Staff ID</th>
                    <th>Class</th>
                    <th>Subject</th>
                    <th>Email</th>
                    <th>Contact</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="checkbox1" name="options[]" value="1">
                        <label for="checkbox1"></label>
                        </span>
                    </td>
                    <td>Ramya</td>
                    <td>RPS101</td>
                    <td>8</td>
                    <td>Maths</td>
                    <td>123@gmail.com</td>
                    <td>7012538010</td>
                    <td>
                        <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="checkbox2" name="options[]" value="1">
                        <label for="checkbox2"></label>
                         </span>
                    </td>
                    <td>Sumith</td>
                    <td>RPS102</td>
                    <td>9</td>
                    <td>English</td>
                    <td>1234@gmail.com</td>
                    <td>7012538010</td>
                    <td>
                        <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="checkbox3" name="options[]" value="1">
                        <label for="checkbox3"></label>
                        </span>
                    </td>
                    <td>Jasmin</td>
                    <td>RPS103</td>
                    <td>10</td>
                    <td>Physics</td>
                    <td>Mini@gmail.com</td>
                    <td>7012538010</td>
                    <td>
                        <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="checkbox4" name="options[]" value="1">
                        <label for="checkbox4"></label>
                        </span>
                    </td>
                    <td>Riyas</td>
                    <td>RPS104</td>
                    <td>9</td>
                    <td>Chemistry</td>
                    <td>Riyas@gmail.com</td>
                    <td>7012538010</td>
                    <td>
                        <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                    </td>
                </tr>     
                <tr>
                    <td>
                        <span class="custom-checkbox">
                        <input type="checkbox" id="checkbox5" name="options[]" value="1">
                        <label for="checkbox5"></label>
                        </span>
                    </td>
                    <td>Prajosh</td>
                    <td>RPS105</td>
                    <td>10</td>
                    <td>Hindhi</td>
                    <td>Praj@gmail.com</td>
                    <td>7012538010</td>
                    <td>
                        <a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                        <a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                    </td>
                </tr> 
            </tbody>
        </table>
        
        <!-- table next and previous -->
        <div class="clearfix">
            <div class="hint-text">Showing <b>5</b> out of <b>30</b> entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item active"><a href="#" class="page-link">3</a></li>
                    <li class="page-item"><a href="#" class="page-link">4</a></li>
                    <li class="page-item"><a href="#" class="page-link">5</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div>
        </div>
    </div>
 
 
 
 <!-- Delete Modal HTML -->
 <div id="deleteEmployeeModal" class="modal fade">
  <div class="modal-dialog">
   <div class="modal-content">
    <form>
     <div class="modal-header">      
      <h4 class="modal-title">Delete Employee</h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
     </div>
     <div class="modal-body">     
      <p>Are you sure you want to delete these Records?</p>
      <p class="text-warning"><small>This action cannot be undone.</small></p>
     </div>
     <div class="modal-footer">
      <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
      <input type="submit" class="btn btn-danger" value="Delete">
     </div>
    </form>
   </div>
  </div>
 </div>


                    
{% endblock %}

app1/templates/admission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADMISSION</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-2 bg-transparent">

        <div class="row sticky-top" style="background-color: rgb(16, 16, 90);">
            <div class="col-lg-1 col-sm-2 logo h1 pt-1"><img class="img-fluid" src="/static/images/logo.png" ></div>
            <div class="col-lg-6 col-sm-6 pt-3 font-weight-bold text-primary"><p class="h2">ROYAL PUBLIC SCHOOL<p style="color: white;">(location)</p></p></div>
            <!-- <div class="col-lg-4 text-right pt-5 text-end" >contact us</div> -->
        </div>

        
        <div class="row">
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand disabled" href="#"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'app1:index' %}">Home</a>
                  </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'app1:about' %}">About</a>
                  </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <li class="nav-item">
                    <a class="nav-link active"  href="{% url 'app1:admission' %}">Admission</a>
                  </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <li class="nav-item">
                    <a class="nav-link active"  href="{% url 'app1:gallery' %} ">Gallery</a>
                  </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <li class="nav-item">
                    <a class="nav-link active"  href="{% url 'app1:login' %}">ERP</a>
                  </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <li class="nav-item">
                    <a class="nav-link active" href="#">Contact us</a>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        </div>



        <div class="row">
          <div class="col-lg-12" style="background-color: rgb(152, 235, 235);">
            <marquee direction="left">The exam will started on 11/02/2022........</marquee>
          </div>
        </div>

        <div class="row">
            <div  class="col-lg-12" style="height: 150px;background-color: rgb(51, 48, 48);">
                <p style="color: white;margin-top: 100px;padding-left: 10px;font-size: large;" ><b>Admission</b></p>
            </div>
        </div>

        <div class="row">
          <div class="col-lg-5 pt-5 ms-5 me-5">
              <p class="h5 fw-bold"><u>High school</u></p>
              <p>Enquiry Form</p>

              <!-- to do...
              enquiry form using bootstarp -->
                    <table class="table table-hover table-warning" style="text-align: center;">
                        <h5 class="text-center">Classes</h5>
                        <thead>
                          <tr>
                            <th scope="col"></th>
                            <th scope="col">division</th>
                            <th scope="col">strength</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row" rowspan="3" class="pt-5">8th</th>
                            <td>A</td>
                            <td>30</td>
                            
                          </tr>
                          <tr>
                            <td>B</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <td>C</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <th scope="row" rowspan="3" class="pt-5">9th</th>
                            <td >A</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <td>B</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <td>C</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <th scope="row" rowspan="3" class="pt-5">10th</th>
                            <td >A</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <td>B</td>
                            <td>30</td>
                          </tr>
                          <tr>
                            <td>C</td>
                            <td>30</td>
                          </tr>
                        </tbody>
                        <tfoot>
                         <th scope="row" colspan="2">Toatal strength</th>
                         <td>270</td>
                        </tfoot>
                      </table>
                </div>
          
          <div class="col-lg-5 pt-5 ms-5">
            <p class="h5 fw-bold"><u>Higher Secondary</u></p>
            <p>Enquiry Form</p>

            <!-- enquiry form using bootstrap(modal) -->

            <p class="h4">Program offered</p><hr>
            <p class="fw-bolder">Biology Science</p><hr>
            <p class="fst-italic">Course code:</p>
            <p class="fst-italic">Duration</p>
            <p class="fst-italic">Total Seats</p><hr>
            <p class="fw-bolder">Commerce</p><hr>
            <p class="fst-italic">Course code:</p>
            <p class="fst-italic">Duration</p>
            <p class="fst-italic">Total Seats</p><hr>
            <p class="fw-bolder">Computer Science</p><hr>
            <p class="fst-italic">Course code:</p>
            <p class="fst-italic">Duration</p>
            <p class="fst-italic">Total Seats</p><hr>
            <p class="fw-bolder">Humanities</p><hr>
            <p class="fst-italic">Course code:</p>
            <p class="fst-italic">Duration</p>
            <p class="fst-italic">Total Seats</p>
          </div>
      </div>
            



        
        

    </div>
</body>
</html>

app1/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container mt-2 bg-transparent">
    
            <div class="row" style="background-color: rgb(16, 16, 90);">
                <div class="col-lg-1 col-sm-2 logo h1 pt-1"><img class="img-fluid" src="/static/images/logo.png" ></div>
                <div class="col-lg-6 col-sm-6 pt-3 font-weight-bold text-primary"><p class="h2">ROYAL PUBLIC SCHOOL<p style="color: white;">(location)</p></p></div>
                <!-- <div class="col-lg-4 text-right pt-5 text-end" >contact us</div> -->
            </div>
    
            <div class="row">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                  <div class="container-fluid">
                    <a class="navbar-brand disabled" href="#"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'app1:index' %}">Home</a>
                        </li>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <li class="nav-item">
                          <a class="nav-link active" href="{% url 'app1:about' %}">About</a>
                        </li>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <li class="nav-item">
                          <a class="nav-link active"  href="{% url 'app1:admission' %}">Admission</a>
                        </li>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <li class="nav-item">
                          <a class="nav-link active"  href="{% url 'app1:gallery' %} ">Gallery</a>
                        </li>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <li class="nav-item">
                          <a class="nav-link active"  href="{% url 'app1:login' %}">ERP</a>
                        </li>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <li class="nav-item">
                          <a class="nav-link active" href="#">Contact us</a>
                        </li>
                      </ul>
                      <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                      </form>
                    </div>
                  </div>
                </nav>
              </div>
    
            <div class="row">
              <div class="col-lg-12" style="background-color: rgb(152, 235, 235);">
                <marquee direction="left">The exam will started on 11/02/2022........</marquee>
              </div>
            </div>
    
            <div class="row">
                <div  class="col-lg-12" style="height: 150px;background-color: rgb(51, 48, 48);">
                    <p style="color: white;margin-top: 100px;padding-left: 10px;font-size: large;" ><b>Gallery</b></p>
                </div>
            </div>





   
        </div>     
</body>
</html>